"""esquema_inicial_uuid7

Revision ID: bd5f8e7d7313
Revises: 
Create Date: 2026-02-07 19:45:12.331781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd5f8e7d7313'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etl_execution',
    sa.Column('execution_type', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('entity', sa.String(length=50), nullable=True),
    sa.Column('window_start', sa.DateTime(), nullable=True),
    sa.Column('window_end', sa.DateTime(), nullable=True),
    sa.Column('window_months', sa.Integer(), nullable=True),
    sa.Column('records_processed', sa.Integer(), nullable=True),
    sa.Column('records_inserted', sa.Integer(), nullable=True),
    sa.Column('records_updated', sa.Integer(), nullable=True),
    sa.Column('records_errors', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('execution_time_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_etl_execution_execution_type'), 'etl_execution', ['execution_type'], unique=False)
    op.create_index(op.f('ix_etl_execution_status'), 'etl_execution', ['status'], unique=False)
    op.create_table('etl_job',
    sa.Column('entity', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=1), nullable=True),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity', 'year', 'mes', 'tipo', 'stage', name='uq_etl_job')
    )
    op.create_index('ix_etl_job_pending', 'etl_job', ['status', 'stage'], unique=False)
    op.create_table('finalidad',
    sa.Column('api_id', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('descripcion_norm', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finalidad_api_id'), 'finalidad', ['api_id'], unique=True)
    op.create_table('fondo',
    sa.Column('api_id', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('descripcion_norm', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fondo_api_id'), 'fondo', ['api_id'], unique=True)
    op.create_table('instrumento',
    sa.Column('api_id', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('descripcion_norm', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instrumento_api_id'), 'instrumento', ['api_id'], unique=True)
    op.create_table('objetivo',
    sa.Column('api_id', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('descripcion_norm', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_objetivo_api_id'), 'objetivo', ['api_id'], unique=True)
    op.create_table('organo',
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('id_padre', sa.Uuid(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('nivel1', sa.String(), nullable=True),
    sa.Column('nivel2', sa.String(), nullable=True),
    sa.Column('nivel3', sa.String(), nullable=True),
    sa.Column('nivel1_norm', sa.String(), nullable=True),
    sa.Column('nivel2_norm', sa.String(), nullable=True),
    sa.Column('nivel3_norm', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.ForeignKeyConstraint(['id_padre'], ['organo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organo_codigo'), 'organo', ['codigo'], unique=True)
    op.create_index('ix_organo_niveles', 'organo', ['nivel1_norm', 'nivel2_norm', 'nivel3_norm'], unique=False)
    op.create_table('regimen_ayuda',
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.Column('descripcion_norm', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('descripcion')
    )
    op.create_index(op.f('ix_regimen_ayuda_descripcion_norm'), 'regimen_ayuda', ['descripcion_norm'], unique=True)
    op.create_table('region',
    sa.Column('api_id', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.Column('descripcion_norm', sa.String(), nullable=False),
    sa.Column('id_padre', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.ForeignKeyConstraint(['id_padre'], ['region.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_region_api_id'), 'region', ['api_id'], unique=True)
    op.create_table('reglamento',
    sa.Column('api_id', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('descripcion_norm', sa.String(), nullable=True),
    sa.Column('ambito', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reglamento_api_id'), 'reglamento', ['api_id'], unique=True)
    op.create_table('sector_actividad',
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.Column('descripcion_norm', sa.String(), nullable=True),
    sa.Column('id_padre', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.ForeignKeyConstraint(['id_padre'], ['sector_actividad.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sector_actividad_codigo'), 'sector_actividad', ['codigo'], unique=True)
    op.create_index(op.f('ix_sector_actividad_descripcion_norm'), 'sector_actividad', ['descripcion_norm'], unique=False)
    op.create_table('sector_producto',
    sa.Column('api_id', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('descripcion_norm', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sector_producto_api_id'), 'sector_producto', ['api_id'], unique=True)
    op.create_table('sync_control',
    sa.Column('fecha_desde', sa.Date(), nullable=False),
    sa.Column('fecha_hasta', sa.Date(), nullable=False),
    sa.Column('inserts_detectados', sa.Integer(), nullable=True),
    sa.Column('updates_detectados', sa.Integer(), nullable=True),
    sa.Column('deletes_detectados', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_control_created_at'), 'sync_control', ['created_at'], unique=False)
    op.create_index(op.f('ix_sync_control_estado'), 'sync_control', ['estado'], unique=False)
    op.create_table('tipo_beneficiario',
    sa.Column('api_id', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('descripcion_norm', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipo_beneficiario_api_id'), 'tipo_beneficiario', ['api_id'], unique=True)
    op.create_table('beneficiario',
    sa.Column('nif', sa.String(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('nombre_norm', sa.String(), nullable=False),
    sa.Column('tipo_beneficiario_id', sa.Uuid(), nullable=True),
    sa.Column('forma_juridica', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['tipo_beneficiario_id'], ['tipo_beneficiario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_beneficiario_created_at'), 'beneficiario', ['created_at'], unique=False)
    op.create_index(op.f('ix_beneficiario_nif'), 'beneficiario', ['nif'], unique=False)
    op.create_table('convocatoria',
    sa.Column('codigo_bdns', sa.String(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('presupuesto_total', sa.Float(), nullable=True),
    sa.Column('fecha_recepcion', sa.Date(), nullable=True),
    sa.Column('organo_id', sa.Uuid(), nullable=True),
    sa.Column('reglamento_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['organo_id'], ['organo.id'], ),
    sa.ForeignKeyConstraint(['reglamento_id'], ['reglamento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_convocatoria_codigo_bdns'), 'convocatoria', ['codigo_bdns'], unique=True)
    op.create_index(op.f('ix_convocatoria_created_at'), 'convocatoria', ['created_at'], unique=False)
    op.create_table('concesion',
    sa.Column('id_concesion', sa.String(), nullable=False),
    sa.Column('fecha_concesion', sa.Date(), nullable=True),
    sa.Column('importe', sa.Float(), nullable=True),
    sa.Column('convocatoria_id', sa.Uuid(), nullable=False),
    sa.Column('beneficiario_id', sa.Uuid(), nullable=False),
    sa.Column('regimen_ayuda_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['beneficiario_id'], ['beneficiario.id'], ),
    sa.ForeignKeyConstraint(['convocatoria_id'], ['convocatoria.id'], ),
    sa.ForeignKeyConstraint(['regimen_ayuda_id'], ['regimen_ayuda.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_concesion_created_at'), 'concesion', ['created_at'], unique=False)
    op.create_index(op.f('ix_concesion_id_concesion'), 'concesion', ['id_concesion'], unique=True)
    op.create_table('pseudonimo',
    sa.Column('beneficiario_id', sa.Uuid(), nullable=False),
    sa.Column('pseudonimo', sa.String(), nullable=False),
    sa.Column('pseudonimo_norm', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.ForeignKeyConstraint(['beneficiario_id'], ['beneficiario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('beneficiario_id', 'pseudonimo_norm', name='uq_beneficiario_pseudonimo')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pseudonimo')
    op.drop_index(op.f('ix_concesion_id_concesion'), table_name='concesion')
    op.drop_index(op.f('ix_concesion_created_at'), table_name='concesion')
    op.drop_table('concesion')
    op.drop_index(op.f('ix_convocatoria_created_at'), table_name='convocatoria')
    op.drop_index(op.f('ix_convocatoria_codigo_bdns'), table_name='convocatoria')
    op.drop_table('convocatoria')
    op.drop_index(op.f('ix_beneficiario_nif'), table_name='beneficiario')
    op.drop_index(op.f('ix_beneficiario_created_at'), table_name='beneficiario')
    op.drop_table('beneficiario')
    op.drop_index(op.f('ix_tipo_beneficiario_api_id'), table_name='tipo_beneficiario')
    op.drop_table('tipo_beneficiario')
    op.drop_index(op.f('ix_sync_control_estado'), table_name='sync_control')
    op.drop_index(op.f('ix_sync_control_created_at'), table_name='sync_control')
    op.drop_table('sync_control')
    op.drop_index(op.f('ix_sector_producto_api_id'), table_name='sector_producto')
    op.drop_table('sector_producto')
    op.drop_index(op.f('ix_sector_actividad_descripcion_norm'), table_name='sector_actividad')
    op.drop_index(op.f('ix_sector_actividad_codigo'), table_name='sector_actividad')
    op.drop_table('sector_actividad')
    op.drop_index(op.f('ix_reglamento_api_id'), table_name='reglamento')
    op.drop_table('reglamento')
    op.drop_index(op.f('ix_region_api_id'), table_name='region')
    op.drop_table('region')
    op.drop_index(op.f('ix_regimen_ayuda_descripcion_norm'), table_name='regimen_ayuda')
    op.drop_table('regimen_ayuda')
    op.drop_index('ix_organo_niveles', table_name='organo')
    op.drop_index(op.f('ix_organo_codigo'), table_name='organo')
    op.drop_table('organo')
    op.drop_index(op.f('ix_objetivo_api_id'), table_name='objetivo')
    op.drop_table('objetivo')
    op.drop_index(op.f('ix_instrumento_api_id'), table_name='instrumento')
    op.drop_table('instrumento')
    op.drop_index(op.f('ix_fondo_api_id'), table_name='fondo')
    op.drop_table('fondo')
    op.drop_index(op.f('ix_finalidad_api_id'), table_name='finalidad')
    op.drop_table('finalidad')
    op.drop_index('ix_etl_job_pending', table_name='etl_job')
    op.drop_table('etl_job')
    op.drop_index(op.f('ix_etl_execution_status'), table_name='etl_execution')
    op.drop_index(op.f('ix_etl_execution_execution_type'), table_name='etl_execution')
    op.drop_table('etl_execution')
    # ### end Alembic commands ###
